services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: youna
    volumes:
      - ./infra/db/certs:/etc/mysql/ssl
    ports:
      - "3306:3306"
